# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    intakeyear.class : AppBundle\Library\GetIntakeYear

services:
    intakeyear_utility:
        class:        %intakeyear.class%
        arguments : []
